create avm law resource module
Azure/terraform-azurerm-avm-res-operationalinsights-workspace pull request #1
Opened 2023-11-11 21:45 UTC by cshea-msft

2023-12-16 08:25 UTC, mbilalamjad commented
Please update the locals.telemetry.tf file

2023-12-16 08:38 UTC, mbilalamjad requested changes
Hey @cshea-msft just reviewed and requested changes with feedback and comments, let me know if you have any questions

2023-12-16 08:38 UTC, mbilalamjad commented on locals.tf
> +
enable_telemetry is already defined as a variable with default value true in variable.tf, you would need to updated main.telemetry.tf line 2 accordingly to use var.enable_telemetry instead and I see that locals.telemetry.tf hasn't been updated

2023-12-16 08:38 UTC, mbilalamjad commented on _header.md
Would recommend to add the following in the header

"Major version Zero (0.y.z) is for initial development. Anything MAY change at any time. The module SHOULD NOT be considered stable till at least it is major version one (1.0.0) or greater. Changes will always be via new versions being published and no changes will be made to existing published versions. For more details please go to https://semver.org/"

2023-12-16 08:38 UTC, mbilalamjad commented on .terraform.lock.hcl
Would recommend double checking your .gitignore file (example below) as this file should have been skipped
https://github.com/Azure/terraform-azurerm-avm-res-network-natgateway/blob/main/.gitignore

2023-12-16 08:38 UTC, mbilalamjad commented on .github/CODEOWNERS
In case you're a single owner you could skip the below additions to allow yourself to be able to do manage and maintain your module once published. In case you have a second owners who's able to work with you to review, approve and merge PRs then the below additions should be fine.

2023-12-18 16:07 UTC, cshea-msft commented on variables.tf
> +
added the description

2023-12-18 16:10 UTC, cshea-msft commented on variables.tf
> +
Yes i did have the possible sku values but it kept erroring out saying it wouldn't take it so I had to remove it for the validate to pass. I will try again

2023-12-18 18:30 UTC, cshea-msft commented on variables.tf
thanks for the suggestion, deployed using the tool.

2023-12-18 18:30 UTC, cshea-msft commented on variables.tf
> +variable "diagnostic_settings" {
fixed by deploying the newser tool

2023-12-18 18:37 UTC, cshea-msft commented on _header.md
added!

2023-12-18 18:38 UTC, cshea-msft commented on .terraform.lock.hcl
updated gitignore

2023-12-18 18:38 UTC, cshea-msft commented on _header.md
updated header

2023-12-18 18:39 UTC, cshea-msft commented on variables.tf
ran the tool and updated code

2023-12-18 19:04 UTC, cshea-msft commented on main.tf
> +
fixed and updated!

2023-12-19 14:36 UTC, cshea-msft commented
Need to close this PR, the commits are not showing up in PR. Will open a new one.

2023-12-19 14:36 UTC, closed without merging